export const basicComponents = [
    // {
    //     type: 'formName',
    //     name: 'Перезвоним через 2 минуты',
    // },
    {
        type: 'title',
        name: 'Заголовок',
        icon: 'icon-title',
        label: 'Заголовок',
    },
    {
        type: 'someText',
        name: 'Обычный текст',
        icon: 'icon-wenzishezhi',
        label: 'Текст',
    },
    {
        type: 'input',
        name: 'Обычное поле',
        icon: 'icon-input',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: '',
            defaultValue: '',
            placeholder: '',
            required: false,
            disabled: false,
        },
    },
    {
        type: 'number',
        name: 'Числовое поле',
        icon: 'icon-number',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: '',
            defaultValue: '',
            placeholder: '',
            min: '',
            max: '',
            step: 1,
            required: false,
            disabled: false,
        },
    },
    {
        type: 'select',
        name: 'Выпадающий список',
        icon: 'icon-tabs',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: '',
            defaultValue: '',
            multiple: false,
            required: false,
            disabled: false,
            showLabel: false,
            options: [
                {
                    value: 'Заголовок',
                },
                {
                    value: 'Опция 1',
                },
                {
                    value: 'Опция 2',
                },
                {
                    value: 'Опция 3',
                },
            ],
            remote: false,
            filterable: false,
            remoteOptions: [],
            props: {
                value: 'value',
                label: 'label',
            },
            remoteFunc: '',
        },
    },
    {
        type: 'name',
        name: 'Имя',
        icon: 'icon-user1',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'name',
            width: '100%',
            defaultValue: '',
            required: false,
            dataType: 'string',
            pattern: '',
            placeholder: 'Впишите имя',
            disabled: false,
        },
    },
    {
        type: 'phone',
        name: 'Телефон',
        icon: 'icon-phone',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'phone',
            width: '100%',
            defaultValue: '',
            required: false,
            dataType: 'string',
            pattern: '',
            placeholder: 'Впишите телефон',
            disabled: false,
        },
    },
    {
        type: 'email',
        name: 'Email',
        icon: 'icon-185078emailmailstreamline',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'email',
            width: '100%',
            defaultValue: '',
            required: false,
            dataType: 'string',
            pattern: '',
            placeholder: 'Впишите email',
            disabled: false,
        },
    },
    {
        type: 'textarea',
        name: 'Сообщение',
        icon: 'icon-8textarea',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'message',
            width: '100%',
            defaultValue: '',
            required: false,
            disabled: false,
            pattern: '',
            placeholder: 'Сообщение',
        },
    },
    {
        type: 'date',
        name: 'Дата',
        icon: 'icon-date',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            defaultValue: '',
            readonly: false,
            disabled: false,
            editable: true,
            clearable: true,
            placeholder: '',
            startPlaceholder: '',
            endPlaceholder: '',
            type: 'date',
            format: 'yyyy-MM-dd',
            timestamp: false,
            required: false,
            width: '',
        },
    },
    {
        type: 'time',
        name: 'Время',
        icon: 'icon-clock',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            defaultValue: '21:19:56',
            readonly: false,
            disabled: false,
            editable: true,
            clearable: true,
            placeholder: '',
            startPlaceholder: '',
            endPlaceholder: '',
            isRange: false,
            arrowControl: true,
            format: 'HH:mm:ss',
            required: false,
            width: '',
        },
    },
    {
        type: 'radio',
        name: 'Радио кнопки',
        icon: 'icon-radio',
        label: 'Заголовок',
        options: {
            inline: false,
            defaultValue: '',
            showLabel: false,
            options: [
                {
                    value: 'Option 1',
                    label: 'Option 1',
                },
                {
                    value: 'Option 2',
                    label: 'Option 2',
                },
                {
                    value: 'Option 3',
                    label: 'Option 3',
                },
            ],
            required: false,
            width: '',
            remote: false,
            remoteOptions: [],
            props: {
                value: 'value',
                label: 'label',
            },
            remoteFunc: '',
            disabled: false,
        },
    },
    {
        type: 'checkbox',
        name: 'Чекбокс кнопки',
        icon: 'icon-checkboxoutline',
        label: 'Заголовок',
        options: {
            inline: false,
            defaultValue: [],
            showLabel: false,
            name: 'checkbox',
            options: [
                {
                    value: 'Option 1',
                },
                {
                    value: 'Option 2',
                },
                {
                    value: 'Option 3',
                },
            ],
            required: false,
            width: '',
            remote: false,
            remoteOptions: [],
            props: {
                value: 'value',
                label: 'label',
            },
            remoteFunc: '',
            disabled: false,
        },
    },
    {
        type: 'slider',
        name: 'Слайдер',
        icon: 'icon-sliders-h',
        label: 'Заголовок',
        options: {
            defaultValue: 0,
            disabled: false,
            required: false,
            min: 0,
            max: 100,
            step: 1,
            showInput: false,
            range: false,
            width: '',
        },
    },
    {
        type: 'button',
        name: 'Кнопка',
        icon: 'icon-mtbutton',
        options: {
            defaultValue: 'Отправить'
        },
    },
];
