export const basicComponents = [
    {
        type: 'title',
        name: 'Заголовок формы',
        icon: 'icon-title',
        label: 'Заголовок',
        classNameLabel: 'cForm_item-wrapper-title',
        style: {
            textAlign: 'left',
            fontSize: 20,
            fontWeight: 400,
            color: '#000',
            marginTop: 0,
            marginBottom: 10,
        }
    },
    {
        type: 'someText',
        name: 'Обычный текст',
        icon: 'icon-wenzishezhi',
        label: 'Текст',
        classNameLabel: 'cForm_item-wrapper-title',
        style: {
            textAlign: 'left',
            fontSize: 20,
            fontWeight: 400,
            color: '#000',
            marginTop: 0,
            marginBottom: 10,
        }
    },
    {
        type: 'input',
        name: 'Обычное поле',
        icon: 'icon-input',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            defaultValue: '',
            placeholder: '',
            required: false,
            disabled: false,
        },
    },
    {
        type: 'number',
        name: 'Числовое поле',
        icon: 'icon-number',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            defaultValue: '',
            placeholder: '',
            min: '',
            max: '',
            step: 1,
            required: false,
            disabled: false,
        },
    },
    {
        type: 'select',
        name: 'Выпадающий список',
        icon: 'icon-tabs',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            defaultValue: 'Заголовок',
            multiple: false,
            required: false,
            disabled: false,
            showLabel: false,
            options: [
                {
                    label: 'Заголовок',
                    value: 'Заголовок'
                },
                {
                    value: 'Опция 1',
                    label: 'Опция 1',
                },
                {
                    value: 'Опция 2',
                    label: 'Опция 2',
                },
                {
                    value: 'Опция 3',
                    label: 'Опция 3',
                },
            ],
            remote: false,
            filterable: false,
            remoteOptions: [],
            props: {
                value: 'value',
                label: 'label',
            },
            remoteFunc: '',
        },
    },
    {
        type: 'name',
        name: 'Имя',
        icon: 'icon-user1',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'name',
            width: '100%',
            defaultValue: '',
            dataType: 'string',
            pattern: '',
            placeholder: 'Впишите имя',
            required: false,
            disabled: false,
        },
    },
    {
        type: 'phone',
        name: 'Телефон',
        icon: 'icon-phone',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'phone',
            width: '100%',
            defaultValue: '',
            required: false,
            dataType: 'string',
            pattern: '',
            placeholder: 'Впишите телефон',
            disabled: false,
            maskValue: '',
            maskAttr: "'mask': ",
            maskRules: [
                {
                    value: null,
                    label: 'Нет',
                },
                {
                    value: "'+375(99) 999-99-99'",
                    label: 'Белорусский номер',
                },
                {
                    value: "'+7(999) 999-99-99'",
                    label: 'Российский номер',
                },
            ],
        },
    },
    {
        type: 'email',
        name: 'Email',
        icon: 'icon-185078emailmailstreamline',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'email',
            width: '100%',
            defaultValue: '',
            required: false,
            dataType: 'string',
            pattern: '',
            placeholder: 'Впишите email',
            disabled: false,
        },
    },
    {
        type: 'textarea',
        name: 'Сообщение',
        icon: 'icon-8textarea',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            name: 'message',
            width: '100%',
            defaultValue: '',
            required: false,
            disabled: false,
            pattern: '',
            placeholder: 'Сообщение',
        },
        style: {
            height: '50'
        }
    },
    {
        type: 'date',
        name: 'Дата',
        icon: 'icon-date',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            type: 'date',
            defaultValue: '',
            disabled: false,
            placeholder: '',
            format: 'yyyy-MM-dd',
            required: false,
        },
    },
    {
        type: 'time',
        name: 'Время',
        icon: 'icon-clock',
        label: 'Заголовок',
        bgIcon: true,
        className: '',
        options: {
            type: 'time',
            defaultValue: '12:00',
            disabled: false,
            placeholder: '',
            format: 'HH:mm',
            required: false,
        },
    },
    {
        type: 'radio',
        name: 'Радио кнопки',
        icon: 'icon-radio',
        label: 'Заголовок',
        options: {
            defaultValue: '',
            inline: false,
            showLabel: false,
            options: [
                {
                    value: 'Опция 1',
                    label: 'Опция 1',
                },
                {
                    value: 'Опция 2',
                    label: 'Опция 2',
                },
                {
                    value: 'Опция 3',
                    label: 'Опция 3',
                },
            ],
            required: false,
            width: '',
            remote: false,
            remoteOptions: [],
            props: {
                value: 'value',
                label: 'label',
            },
            remoteFunc: '',
        },
    },
    {
        type: 'checkbox',
        name: 'Чекбокс кнопки',
        icon: 'icon-checkboxoutline',
        label: 'Заголовок',
        options: {
            inline: false,
            defaultValue: [],
            showLabel: false,
            options: [
                {
                    value: 'Опция 1',
                    label: 'Опция 1',
                },
                {
                    value: 'Опция 2',
                    label: 'Опция 2',
                },
                {
                    value: 'Опция 3',
                    label: 'Опция 3',
                },
            ],
            required: false,
            width: '',
            remote: false,
            remoteOptions: [],
            props: {
                value: 'value',
                label: 'label',
            },
            remoteFunc: '',
        },
    },
    {
        type: 'slider',
        name: 'Слайдер',
        icon: 'icon-sliders-h',
        label: 'Заголовок',
        options: {
            defaultValue: 0,
            disabled: false,
            required: false,
            min: 0,
            max: 100,
            step: 1,
            width: '',
        },
    },
    {
        type: 'button',
        name: 'Кнопка',
        icon: 'icon-mtbutton',
        options: {
            defaultValue: 'Отправить'
        },
    },
];
